apiVersion: v1
kind: Service
metadata:
  name: firefox-service
  namespace: development
spec:
  ports:
    - name: TCP
      port: 80
      targetPort: 8083
  type: LoadBalancer    
  selector:
    apps: firefox-app