apiVersion: v1
kind: Service
metadata:
  name: firefox-service
#  namespace: development
spec:
  ports:
    - name: TCP
      port: 80
      targetPort: 9091
  type: LoadBalancer    
  selector:
    apps: firefox-app