apiVersion: v1
kind: Pod
metadata:
  name: staticApp
  labels:
    app: staticApp
spec:
  containers:
    - name: staticApp
      image: aakankshi/hnproject:latest
      ports:
        - containerPort: 9091