apiVersion: v1
kind: Pod
metadata:
  name: static-app
  labels:
    app: static-app
spec:
  containers:
    - name: static-app
      image: aakankshi/hnproject:{{GIT_COMMIT}}
      ports:
        - containerPort: 80